// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDevice(arg1) {
  return window['go']['main']['App']['AddDevice'](arg1);
}

export function DeleteDevice(arg1) {
  return window['go']['main']['App']['DeleteDevice'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function StartSimulation() {
  return window['go']['main']['App']['StartSimulation']();
}

export function StopSimulation() {
  return window['go']['main']['App']['StopSimulation']();
}
