// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {simulator} from '../models';

export function AddDevice(arg1:string):Promise<void>;

export function DeleteDevice(arg1:number):Promise<void>;

export function GetConfig():Promise<simulator.SimulatorConfig>;

export function SaveConfig(arg1:simulator.SimulatorConfig):Promise<void>;

export function StartSimulation():Promise<void>;

export function StopSimulation():Promise<void>;
